<a href="https://colab.research.google.com/github/Hasnien/ML-Learning-Roadmap/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ages= np.array([21,22,23,24,25])
print(ages)

[21 22 23 24 25]


In [ ]:
a=np.array((2,4,6))
b=np.array((8,10,12))

print(a+b)
print(type(a))
print(a.ndim)
print(a.shape)

[10 14 18]
<class 'numpy.ndarray'>
1
(3,)


In [ ]:
d2_array = np.array([[1,2,3],[4,5,6]])
print(d2_array)
print(d2_array.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
d3_array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d3_array)
print(d3_array.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
arr = np.array([
                [["a","b","c"],
                 ["d","e","f"],
                 ["g","h","i"]],

                [["a","b","c"],
                 ["d","e","f"],
                 ["g","h","i"]],


                [["a","b","c"],
                 ["d","e","f"],
                 ["g","h","i"]]

                ])
print(type(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
3
(3, 3, 3)


**Mini Project**

In [1]:
#creating a sample dataset

import numpy as np
scores = np.array([
    [70,80,90],
    [60,75,85],
    [90,95,100],
    [55,65,70],
    [85,90,95]
])
print(scores)
print(scores.ndim)
print(scores.shape)

[[ 70  80  90]
 [ 60  75  85]
 [ 90  95 100]
 [ 55  65  70]
 [ 85  90  95]]
2
(5, 3)


===== STUDENT PERFORMANCE ANALYZER =====

Overall Average: ...
Highest Score: ...
Lowest Score: ...
Median Score: ...
Standard Deviation: ...

Subject Averages:
Math: ...
English: ...
Science: ...

Student Averages:
Student 1: ...
Student 2: ...
Student 3: ...
Student 4: ...
Student 5: ...

Top Student: Student ...
Passed: ...
Failed: ...

Scores After 5-Point Bonus:
...

In [8]:
"""Column 0 → Math
Column 1 → English
Column 2 → Science"""

"""Row 0 → Student 1
Row 1 → Student 2
Row 2 → Student 3
Row 3 → Student 4
Row 4 → Student 5"""

#overall average of students
print("Overall Average: ",np.mean(scores))

#highest score
print("Highest Score: ",np.max(scores))
#lowest score
print("Lowest Score: ",np.min(scores))
#median
print("Median Score: ",np.median(scores))
#Standard deviation
print("Standard Deviation: ",np.std(scores))

Overall Average:  80.33333333333333
Highest Score:  100
Lowest Score:  55
Median Score:  85.0
Standard Deviation:  13.349989596333856


In [11]:
#Subject-wise averages

#math average
print("Math Average: ",np.mean(scores[:,0]))
#eng average
print("English Average: ",np.mean(scores[:,1]))
#science average
print("Science Average: ",np.mean(scores[:,2]))


Math Average:  72.0
English Average:  81.0
Science Average:  88.0


In [15]:
#student wise averag
print("Student 1 Average: ",np.mean(scores[0,:]))
print("Student 2 Average: ",np.mean(scores[1,:]))
print("Student 3 Average: ",np.mean(scores[2,:]))
print("Student 4 Average: ",np.mean(scores[3,:]))
print("Student 5 Average: ",np.mean(scores[4,:]))

Student 1 Average:  80.0
Student 2 Average:  73.33333333333333
Student 3 Average:  95.0
Student 4 Average:  63.333333333333336
Student 5 Average:  90.0


In [14]:
#find top student
print("Top Student: ",np.max(np.mean(scores,axis=1)))

Top Student:  95.0


Let's say:

A student passes if their average score is 65 or higher.

In [18]:
passed = np.where(np.mean(scores,axis=1)>=65)
print("Passed: ",passed)
failed = np.where(np.mean(scores,axis=1)<65)
print("Failed: ",failed)

Passed:  (array([0, 1, 2, 4]),)
Failed:  (array([3]),)


Add a 5-point bonus

In [19]:
scores_bonus = scores + 5
print(scores_bonus)


[[ 75  85  95]
 [ 65  80  90]
 [ 95 100 105]
 [ 60  70  75]
 [ 90  95 100]]
